# Generated by Django 5.0.6 on 2024-05-30 15:01

import django.db.models.deletion
import timezone_field.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_server', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('email_password', models.CharField(max_length=100)),
                ('imap_port', models.IntegerField()),
                ('auto_import_mails_as_tickets', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Imap Email Setup - (Incoming)',
            },
        ),
        migrations.CreateModel(
            name='OutgoinEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_reply_email_name', models.CharField(blank=True, default='ICT Helpdesk', max_length=255, null=True)),
                ('support_reply_email', models.EmailField(blank=True, default='titusowuor30@gmail.com', max_length=255, null=True)),
                ('email_password', models.CharField(blank=True, default='xdofqrtncuimlewm', max_length=255, null=True)),
                ('email_port', models.IntegerField(blank=True, default=587, null=True)),
                ('email_backed', models.CharField(blank=True, default='smtp', max_length=100, null=True)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True)),
                ('fail_silently', models.BooleanField(blank=True, default=True, null=True)),
                ('use_tls', models.BooleanField(blank=True, default=True, null=True)),
                ('code_place_holders', models.TextField(blank=True, max_length=25000, null=True)),
                ('send_auto_email_on_ticket_creation', models.BooleanField(blank=True, default=True, null=True)),
                ('auto_assign_tickets', models.BooleanField(blank=True, default=True, null=True)),
                ('code_for_automated_reply', models.TextField(blank=True, max_length=25000, null=True)),
                ('send_auto_email_on_agent_reply', models.BooleanField(blank=True, default=True, null=True)),
                ('send_auto_email_on_agent_assignment', models.BooleanField(blank=True, default=True, null=True)),
                ('code_for_automated_assign', models.TextField(blank=True, max_length=25000, null=True)),
                ('code_for_agent_reply', models.TextField(blank=True, max_length=25000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Support Email Setup - (Outgoing)',
            },
        ),
        migrations.CreateModel(
            name='System_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('site_title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_text_color', models.CharField(blank=True, choices=[('light', 'light'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('dark', 'dark'), ('default', 'default')], default='primary', max_length=10, null=True)),
                ('logo_bg', models.CharField(blank=True, choices=[('light', 'light'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('dark', 'dark'), ('default', 'default')], default='light', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default='info@masterspace.co.ke', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='36779-00200', max_length=100, null=True)),
                ('company', models.CharField(blank=True, default='Gokhan Masterspace JV Limited', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, default='+254743793901', max_length=15, null=True)),
                ('suite', models.CharField(blank=True, default='First Floor Birdir Complex,', max_length=100, null=True)),
                ('road', models.CharField(blank=True, default='Mombasa Road', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Kenya', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ticket_escalltion', models.BooleanField(blank=True, default=True, null=True)),
                ('time_zone', timezone_field.fields.TimeZoneField(default='Africa/Nairobi', use_pytz=True)),
                ('duration_before_escallation', models.IntegerField(default=48, help_text='Time in hours')),
                ('code_place_holders', models.TextField(blank=True, max_length=25000, null=True)),
                ('code_for_automated_escallation_email', models.TextField(blank=True, max_length=25000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket Settings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=8, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('issue_description', tinymce.models.HTMLField(blank=True, max_length=25000, null=True)),
                ('customer_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.EmailField(default='example@example.com', max_length=40)),
                ('ticket_section', models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database', 'Database'), ('Technical', 'Technical'), ('HR', 'HR'), ('Administration', 'Administration'), ('Transport', 'Transport'), ('General', 'General')], default='General', max_length=30, null=True)),
                ('ticket_priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=100, null=True)),
                ('ticket_status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Unsolved', 'Unsolved')], default='Unsolved', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='ticketapp.tags')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.ticket')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.ticket')),
            ],
        ),
    ]
