# Generated by Django 3.2.13 on 2022-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imapsettings',
            name='auto_import_mails_as_tickets',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
