# Generated by Django 3.2.13 on 2022-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='code_for_automated_escallation_email',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettings',
            name='code_place_holders',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
    ]
