# Generated by Django 3.2.13 on 2022-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='urgent_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_priority',
            field=models.CharField(blank=True, default='Low', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_section',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database Administrator', 'Database Administrator'), ('Weigh bridge', 'Weigh bridge'), ('Transport', 'Transport'), ('General', 'General')], default='General', max_length=30, null=True),
        ),
    ]
