# Generated by Django 3.2.13 on 2022-08-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20220816_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_full_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_section',
        ),
    ]
