# Generated by Django 3.2.5 on 2022-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20220918_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('site_title', models.CharField(max_length=100)),
            ],
        ),
    ]
