# Generated by Django 3.2.13 on 2022-08-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20220816_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(default='info@tdbsoft.co.ke', max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_section',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database Administrator', 'Database Administrator'), ('Weigh bridge', 'Weigh bridge'), ('Transport', 'Transport'), ('General', 'General')], default='General', max_length=30, null=True),
        ),
    ]
