# Generated by Django 3.2.5 on 2022-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_system_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system_settings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='system_settings',
            name='logo_bg',
            field=models.CharField(blank=True, choices=[('light', 'light'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('default', 'default')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='title_text_color',
            field=models.CharField(blank=True, choices=[('light', 'light'), ('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('default', 'default')], max_length=10, null=True),
        ),
    ]
