# Generated by Django 3.2.13 on 2022-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_alter_comment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
