# Generated by Django 3.2.5 on 2022-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20221110_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='address',
            field=models.EmailField(blank=True, default='36779-00200', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='company',
            field=models.CharField(blank=True, default='Gokhan Masterspace JV Limited', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='city',
            field=models.CharField(blank=True, default='Nairobi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='email',
            field=models.EmailField(blank=True, default='info@masterspace.co.ke', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='road',
            field=models.CharField(blank=True, default='Mombasa Road', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='state',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='suite',
            field=models.CharField(blank=True, default='First Floor Birdir Complex,', max_length=100, null=True),
        ),
    ]
