# Generated by Django 3.2.13 on 2022-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20220816_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_description',
            field=models.TextField(max_length=25000),
        ),
    ]
