# Generated by Django 3.2.13 on 2022-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_alter_ticket_issue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='ticketapp.MediaFiles'),
        ),
    ]
