# Generated by Django 3.2.5 on 2022-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_auto_20221110_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='address',
            field=models.EmailField(blank=True, default='36779-00200', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='email',
            field=models.EmailField(blank=True, default='info@masterspace.co.ke', max_length=100, null=True),
        ),
    ]
