# Generated by Django 3.2.13 on 2022-08-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_auto_20220816_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafiles',
            options={'verbose_name_plural': 'Attachments'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attachments',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.mediafiles'),
        ),
    ]
